name: Rajkot Air Quality Data Collection

on:
  schedule:
    - cron: "*/20 * * * *"
      timezone: "Asia/Kolkata"

  workflow_dispatch:

jobs:
  collect-data:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Collect Rajkot air quality data
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          python collect_data.py
